[package]
name = "brainsuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfunc = { path = "/home/gfunction/Projects/Rust/Lib/gfunc/v0.1", features = ["run"] }

